name: release build
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'     
        required: true
        default: 'v2024.1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/workflows/bootstrap
      - name: Assemble
        uses: ./.github/workflows/assemble
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-fees.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Create release
        run: |
          gh release create ${{ github.event.inputs.tag }} 'android/app/build/outputs/apk/release/app-release.apk#bitcoin-fees.apk' --notes "Release" --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
