name: sanity build
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/workflows/bootstrap
      - name: Install dependencies
        run: npm install
#      - name: Check prettier
#        run: npm run prettier-check
#      - name: Check ESLint
#        run: npm run eslint-check
      - name: Install dependencies
        run: npx expo prebuild --platform android
      - name: Assemble APK
        run: cd android && ./gradlew assembleRelease
