name: sanity build
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: 'v2024.1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      - name: Install dependencies
        run: npm install
#      - name: Check prettier
#        run: npm run prettier-check
#      - name: Check ESLint
#        run: npm run eslint-check
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: 34.0.0
          cmake-version: 3.22.1
          ndk-version: 23.1.7779620
          sdk-version: 34
      - name: Install dependencies
        run: npx expo prebuild --platform android
      - name: Assemble
        run: cd android && ./gradlew assembleRelease
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-fees.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Release APK
        run: |
          gh release create ${{ github.event.inputs.tag }} 'android/app/build/outputs/apk/release/app-release.apk#Bitcoin fees'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
